lang: id

website:
  title: "PBP Gasal 2026/2027"
  navbar:
    background: dark
    left:
      - text: "Jadwal"
        href: index.qmd
      - text: "Materi"
        href: materi/index.qmd
      - text: "Tutorial"
        href: tutorial/index.qmd
      - text: "Tugas"
        href: assignments/index.qmd
    right:
      - text: "Penghargaan"
        href: awards.qmd
      - text: "🇬🇧 English"
        href: en/index.html
      - icon: github
        href: https://github.com/Hafizmuh18/pbp-gasal-2027
        aria-label: GitHub

  sidebar:
    - id: materi
      title: "Materi"
      style: docked
      contents:
        - text: "Informasi"
          href: materi/index.qmd
        - text: "Materi 01: Introduction to Platform-Based Programming"
          href: materi/materi-01.qmd
        - text: "Materi 02: Introduction to the Internet and Web Framework"
          href: materi/materi-02.qmd
        - text: "Materi 03: MTV Django Architecture and Testing"
          href: materi/materi-03.qmd
        - text: "Materi 04: Data Delivery"
          href: materi/materi-04.qmd
    - id: tutorial
      title: "Tutorial"
      style: docked
      contents:
        - text: "Informasi"
          href: tutorial/index.qmd
    - id: assignments
      title: "Tugas"
      style: docked
      contents:
        - text: "Informasi"
          href: assignments/index.qmd
        - section: "Tugas Kelompok"
          contents:
            - text: "Proyek Tengah Semester"
              href: assignments/group/midterm.qmd
            - text: "Panduan Tugas Kelompok"
              href: assignments/group/midterm-guide.qmd
            - text: "Proyek Akhir Semester"
              href: assignments/group/finalterm.qmd

  page-footer:
    left: "Copyright © PBP Fasilkom UI."
    right:
      - icon: github
        href: https://github.com/Hafizmuh18/pbp-gasal-2027
