lang: id

website:
  title: "PBP Gasal 2026/2027"
  navbar:
    background: dark
    left:
      - text: "Jadwal"
        href: index.qmd
      - text: "Materi"
        href: materi/index.qmd
      - text: "Tutorial"
        href: tutorial/index.qmd
      - text: "Tugas"
        href: assignments/index.qmd
    right:
      - text: "🇬🇧 English"
        href: en/index.html

  sidebar:
    - id: materi
      title: "Materi"
      style: docked
      contents:
        - text: "Informasi"
          href: materi/index.qmd
        - text: "Materi 01"
          href: materi/materi-01.qmd
    - id: tutorial
      title: "Tutorial"
      style: docked
      contents:
        - text: "Informasi"
          href: tutorial/index.qmd
        - text: "Tutorial 0: Setup Git Repository, Django Installation"
          href: tutorial/tutorial-0.qmd
        - text: "Tutorial 01: Django Initial Project, HTML5 dan CSS3"
          href: tutorial/tutorial-1.qmd
    - id: assignments
      title: "Tugas"
      style: docked
      contents:
        - text: "Informasi"
          href: assignments/index.qmd
        - section: "Proyek Individu"
          contents:
            - text: "Individual Assignment 1: Static Web with HTML5 and CSS3"
              href: assignments/individual/tugas-1.qmd
        - section: "Tugas Kelompok"
          contents:
            - text: "Proyek Tengah Semester"
              href: assignments/group/midterm.qmd
            - text: "Panduan Tugas Kelompok"
              href: assignments/group/midterm-guide.qmd
            - text: "Proyek Akhir Semester"
              href: assignments/group/finalterm.qmd

  page-footer:
    left: "Copyright © PBP Fasilkom UI - Gasal 2026/2027"
    right:
      - icon: github
        href: https://github.com/Hafizmuh18/pbp-gasal-2027
