project:
  output-dir: _site/en

lang: en

website:
  title: "PBP Odd Semester 2026/2027"
  navbar:
    background: dark
    left:
      - text: "Schedule"
        href: index.qmd
      - text: "Materials"
        href: materi/index.qmd
      - text: "Tutorial"
        href: tutorial/index.qmd
      - text: "Assignments"
        href: assignments/index.qmd
    right:
      - text: "🇮🇩 Indonesia"
        href: ../index.html

  sidebar:
    - id: materi
      title: "Materials"
      style: docked
      contents:
        - text: "Information"
          href: materi/index.qmd
        - text: "Material 01"
          href: materi/materi-01.qmd
        - text: "Material 02"
          href: materi/materi-02.qmd
    - id: tutorial
      title: "Tutorial"
      style: docked
      contents:
        - text: "Information"
          href: tutorial/index.qmd
        - text: "Tutorial 0: Set Up Git Repository, Django Installation"
          href: tutorial/tutorial-0.qmd
        - text: "Tutorial 01: Django Initial Project, HTML5 and CSS3"
          href: tutorial/tutorial-1.qmd
        - text: "Tutorial 2: Model-View-Template (MVT) Django Implementation"
          href: tutorial/tutorial-2.qmd
        - text: "Tutorial 03: Form dan Data Delivery"
          href: tutorial/tutorial-3.qmd

    - id: assignments
      title: "Assignments"
      style: docked
      contents:
        - text: "Information"
          href: assignments/index.qmd
        - section: "Individual Project"
          contents:
            - text: "Individual Assignment 1: Static Web with HTML5 and CSS3"
              href: assignments/individual/tugas-1.qmd
            - text: "Individual Assignment 2: Implementing MVT in Django"
              href: assignments/individual/tugas-2.qmd
            - text: "Individual Assignment 3: Form & Data Delivery"
              href: assignments/individual/tugas-3.qmd
        - section: "Group Assignments"
          contents:
            - text: "Midterm Group Project"
              href: assignments/group/midterm.qmd
            - text: "Group Assignment Guide"
              href: assignments/group/midterm-guide.qmd
            - text: "Final Group Project"
              href: assignments/group/finalterm.qmd

  page-footer:
    left: "Copyright © PBP Fasilkom UI - Odd Semester 2026/2027"
    right:
      - icon: github
        href: https://github.com/pbp-fasilkom-ui/gasal-2027
