---
title: "Penghargaan Aplikasi Tugas Kelompok Terbaik"
---

***

::: {.content-visible when-profile="id"}

## Aplikasi Terbaik (Keduanya)

1. **Ligapass**
    - Tim Pengembang: Kelompok C06

## Aplikasi Web Terbaik

1. **SpeedView**
    - Tim Pengembang: Kelompok C03

## Aplikasi Android Terbaik

1. **Moveez**
    - Tim Pengembang: Kelompok E01

## Desain Terbaik

1. **SpeedView**
    - Tim Pengembang: Kelompok C03

## Aplikasi Terfavorit

Pemenang aplikasi terfavorit ditentukan berdasarkan pilihan mahasiswa, dosen, dan asisten dosen. Urutan aplikasi terfavorit berdasarkan perolehan suara dalam pemilihan di Discord PBP:

1. **Ligapass**
    - Peraih Suara Terbanyak
    - Tim Pengembang: Kelompok C06

    <iframe width="560" height="315" src="https://www.youtube.com/embed/EvyftGBOIik?si=q_zOZ-N32siOoT-b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

2. **Court Finder**
    - Tim Pengembang: Kelompok C01

    <iframe width="560" height="315" src="https://www.youtube.com/embed/r54PmINdepQ?si=XMDddLjQMbrwGgVp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

3. **Sporra**
    - Tim Pengembang: Kelompok D09

    <iframe width="560" height="315" src="https://drive.google.com/file/d/1NmC7WrHl37UcOp_Rr-2zWiheyRN1f6mT/preview" title="Google Drive file" frameborder="0" allow="autoplay" allowfullscreen></iframe>

:::

::: {.content-visible when-profile="en"}

## Best Overall Application (Both)

1. **Ligapass**
    - Development Team: Group C06

## Best Web Application

1. **SpeedView**
    - Development Team: Group C03

## Best Android Application

1. **Moveez**
    - Development Team: Group E01

## Best Design

1. **SpeedView**
    - Development Team: Group C03

## Most Favorite Application

The most favorite application award is decided by student, lecturer, and teaching assistant votes. Ranking based on the number of votes received in the PBP Discord poll:

1. **Ligapass**
    - Most Votes
    - Development Team: Group C06

    <iframe width="560" height="315" src="https://www.youtube.com/embed/EvyftGBOIik?si=q_zOZ-N32siOoT-b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

2. **Court Finder**
    - Development Team: Group C01

    <iframe width="560" height="315" src="https://www.youtube.com/embed/r54PmINdepQ?si=XMDddLjQMbrwGgVp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

3. **Sporra**
    - Development Team: Group D09

    <iframe width="560" height="315" src="https://drive.google.com/file/d/1NmC7WrHl37UcOp_Rr-2zWiheyRN1f6mT/preview" title="Google Drive file" frameborder="0" allow="autoplay" allowfullscreen></iframe>

:::
